import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "@next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Stargram",
  description: "Generated by Stargram.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}